import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import HeaderProvider from "@/context/header";
import Footer from "@/components/ui/Footer";
import BackToTop from "@/components/backToTop";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Bệnh viện Trung ương Huế",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  const cookieStore = await cookies();
  const locale = cookieStore.get("lang")?.value || "vi";

  const titles: Record<string, string> = {
    vi: "Bệnh viện Trung ương Huế",
    eng: "Hue Central Hospital",
  };

  const description: Record<string, string> = {
    vi: "Bệnh viện Trung ương Huế",
    eng: "Hue Central Hospital",
  };

  const title =
    cookieStore.get("title")?.value || (titles[locale] ?? titles.vi);

  return {
    title: title,
    description: description[locale] ?? description.vi,
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies(); // ✅ await
  const locale = cookieStore.get("lang")?.value || "vi";

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
          <HeaderProvider locale={locale}>
            <main className="flex min-h-screen w-full flex-col items-center justify-between bg-white dark:bg-black sm:items-start">
              <Header />
              <div className="w-full pb-16 pt-1 flex flex-col justify-between">
                {children}
              </div>
              <Footer />
            </main>
            <BackToTop />
          </HeaderProvider>
        </div>
      </body>
    </html>
  );
}
